port = "18080"
domain = "127.0.0.1"
group = "default"

[server]
    [server.ds_config]
        [server.ds_config.redis]
        host = "127.0.0.1"
        port = 26379
        username = ""
        password = "1433223"
        [server.ds_config.mongo]
        host = "127.0.0.1"
        port = 37017
        username = "admin"
        password = "1433223"
    [server.jwt]
    secret = "123456"
    expire = 3600
    
    [server.console_jwt]
    secret = "123456"
    expire = 3600
    [server.admin]
    username = "aaron"
    password = "aaron519"

[s3]
    bucket = "file-storage"
    endpoint = "http://127.0.0.1:19000"
    access_key = "admin"
    secret_key = "1433223"
    region = "cn-north"